
#ifndef _AUTO_VERSION_INFORMATION_H_
#define _AUTO_VERSION_INFORMATION_H_

#define SM_BUILD_TAG	 	""
#define SM_BUILD_UNIQUEID	"1:82e55d328c8c" SM_BUILD_TAG
#define SM_VERSION			"1.6.4"
#define SM_FULL_VERSION		SM_VERSION SM_BUILD_TAG
#define SM_FILE_VERSION		1,6,4,0

#endif /* _AUTO_VERSION_INFORMATION_H_ */

